name: Django CI

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
            MYSQL_DATABASE: 'sharkle_test'
            MYSQL_USER: 'sharkle-test'
            MYSQL_PASSWORD: 'seminar'
            MYSQL_ROOT_PASSWORD: password
        ports:
            - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    strategy:
      max-parallel: 4

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.10
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: ./sharkle
    - name: Run Tests
      run: |
        python manage.py test
      env:
          SYSTEM_ENV: GITHUB_WORKFLOW
      working-directory: ./sharkle
